config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "reviews#index"

  get 'info', to: 'static_pages#info', as: :info
  get 'terms', to: 'static_pages#terms', as: :terms
  get 'privacy', to: 'static_pages#privacy', as: :privacy

  # get 'login', to: 'user_sessions#new', as: :login
  # post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  post "/oauth/:provider/callback" => "oauths#callback"
  get "/oauth/:provider/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#oauth", :as => :auth_at_provider

  delete 'delete', to: 'users#destroy', as: :user_delete
  resources :users, only: %i[edit update]

  resources :reviews do
    get 'favorites', on: :collection
  end
  get 'own/:user_id', to: 'reviews#own_reviews', as: :own

  resources :favorites, only: %i[create destroy]

  get 'tags/search', to: 'tags#search'
  get 'tags/all_search', to: 'tags#all_search'
  get 'organizers/search', to: 'organizers#search'
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_one_attached :storage_avatar_image

  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_reviews, through: :favorites, source: :review

  validates :name, presence: true, length: { maximum: 50 }
  validates :twitter_name, presence: true, uniqueness: true
  validates :twitter_id, presence: true, uniqueness: true
  validate :storage_avatar_image_size

  def own?(object)
    self.id == object.user_id
  end

  def favorite(review)
    favorite_reviews << review
  end

  def unfavorite(review)
    favorite_reviews.destroy(review)
  end

  def favorite?(review)
    favorite_reviews.include?(review)
  end

  def storage_avatar_image_size
    if storage_avatar_image.attached? && storage_avatar_image.blob.byte_size > 2.megabytes
      errors.add(:storage_avatar_image, '：2MB以下のファイルをアップロードしてください')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def edit; end

  def update
    @user.storage_avatar_image.purge if params[:storage_avatar_image].present?

    respond_to do |format|
      if @user.update(profile_params)
        format.html { redirect_to edit_user_path, success: t('flash.reviews.success.update') }
        format.json { render :edit, status: :ok, location: @user }
      else
        flash.now[:danger] = t('flash.reviews.failed.update')
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    current_user.destroy!
    redirect_to root_url, success: t('flash.users.delete'), status: :see_other
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def profile_params
    params.require(:user).permit(:name, :public_twitter, :avatar, :storage_avatar_image, :storage_avator_image_cache)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_destroy.html.erb
<!-- Main modal -->
<div id="default-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 mx-auto justify-center items-center w-3/4 max-w-[350px] md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-2xl max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded shadow">
            <!-- Modal header -->
            <div class="flex items-center justify-between px-2 md:px-3 border-b rounded-t">
                <h3 class="text-xl p-2 pt-3">
                    <%= t('users.delete') %>
                </h3>
                <button type="button" class="end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-hide="default-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-4 md:p-5 space-y-4">
                <div class="text-base leading-relaxed">
                    <p class="mb-4 text-sm">
                        <%= t('users.delete_message.') %>
                    </p>
                    <%= link_to t('users.delete_button'), user_delete_path, class: 'text-sm sm:text-base flex items-center justify-center w-full rounded border-2 focus:outline-none focus:border-[rgb(239,123,81)] hover:border-[rgb(239,123,81)] transition py-2', data: { turbo_method: :delete } %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="px-4 md:p-0 pt-8 pb-4 md:m-10 md:mb-0">
  <%= form_with model: @user, url: user_path(@user), local: true do |f| %>
    <%= render partial: 'shared/error_messages', locals: { object: f.object } %>
    <div>
      <div id="image-button" class="block relative min-w-20 w-20 mx-auto cursor-pointer hover:opacity-80">
        <%= image_tag current_user.avatar_img_profile, class: 'rounded-[50%] max-w-full min-w-20 w-20 h-20 mx-auto object-cover' %>
        <div class="absolute bottom-[-0.5em] right-[-8px] fill-white bg-[rgba(115,207,223,0.9)] w-[35px] h-[35px] rounded-[50%] flex items-center justify-center">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="18px"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M149.1 64.8L138.7 96H64C28.7 96 0 124.7 0 160V416c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V160c0-35.3-28.7-64-64-64H373.3L362.9 64.8C356.4 45.2 338.1 32 317.4 32H194.6c-20.7 0-39 13.2-45.5 32.8zM256 192a96 96 0 1 1 0 192 96 96 0 1 1 0-192z"/></svg>
        </div>
      </div>
      <%= f.file_field :storage_avatar_image, accept: 'image/*', id: 'activestorage_avatar_image', class: 'hidden' %>

      <div class="my-6 px-4 flex items-center justify-between gap-8 md:max-w-[70%] md:mx-auto">
          <%= f.label :public_twitter, class: 'text-sm font-medium' %>
          <div class="switchbar inline-block <%= 'checked' if @user.public_twitter %>"><%= f.check_box :public_twitter %></div>
      </div>

      <div class="my-6 px-4 flex items-center justify-between gap-4 md:max-w-[70%] md:mx-auto">
        <%= f.label :name, class: 'text-sm font-medium' %>
        <%= f.text_field :name, class: 'border-[1px] border-gray-200 rounded-lg text-sm text-gray-900 focus:ring-[#c9e8f8] focus:border-[#c9e8f8] p-2.5' %>
      </div>

      <%= f.submit '変更する', class: "block mx-auto align-center w-1/2 md:w-1/3 px-5 py-3 mt-8 text font-medium text-center text-white shadow bg-[rgb(115,207,223)] hover:bg-[rgb(105,189,204)] transition-colors rounded-lg focus:ring-4 focus:ring-[#c9e8f8]" %>
    </div>
  <% end %>

  <div class="mt-12 mb-4 md:mb-0 before:content-[''] before:block before:w-full before:h-[1px] md:before:h-[2px] before:bg-gray-200 before:mb-4 md:before:mb-12 mx-auto">
    <button data-modal-target="default-modal" data-modal-toggle="default-modal" type="button" class="block mx-auto mt-6 align-center w-1/3 md:w-1/4 px-2 py-3 text-xs text-center text-[rgb(239,123,81)] hover:text-white hover:bg-[rgb(239,123,81)] border border-[rgb(239,123,81)] transition-colors rounded-lg">
      <%= t('views.footer.delete') %>
    </button>
  </div>
</div>

<%= render 'users/destroy' %>

<%= javascript_include_tag "image_button.js" %>
<%= javascript_include_tag "switch.js" %>