config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "reviews#index"

  get 'info', to: 'static_pages#info', as: :info
  get 'terms', to: 'static_pages#terms', as: :terms
  get 'privacy', to: 'static_pages#privacy', as: :privacy

  # get 'login', to: 'user_sessions#new', as: :login
  # post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  post "/oauth/:provider/callback" => "oauths#callback"
  get "/oauth/:provider/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#oauth", :as => :auth_at_provider

  delete 'delete', to: 'users#destroy', as: :user_delete
  resources :users, only: %i[edit update]

  resources :reviews do
    get 'favorites', on: :collection
  end
  get 'own/:user_id', to: 'reviews#own_reviews', as: :own

  resources :favorites, only: %i[create destroy]

  get 'tags/search', to: 'tags#search'
  get 'tags/all_search', to: 'tags#all_search'
  get 'organizers/search', to: 'organizers#search'
end

app/views/shared/_before_login_footer.html.erb
<footer id='footer' class="bg-[rgb(166,217,226)] text-white p-4">
  <div class='container text-center mx-auto'>
    <div class="md:flex md:flex-wrap md:gap-6 md:justify-center md:items-center mb-1 text-[0.8rem] md:text-sm">
      <div>
        <%= link_to 'https://github.com/ayuoh/ws-reviews', class: 'fill-white', target: :_blank, rel: "noopener noreferrer" do %>
          <svg xmlns="http://www.w3.org/2000/svg" height="24" width="23.25" viewBox="0 0 496 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3 .3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5 .3-6.2 2.3zm44.2-1.7c-2.9 .7-4.9 2.6-4.6 4.9 .3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3 .7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3 .3 2.9 2.3 3.9 1.6 1 3.6 .7 4.3-.7 .7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3 .7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3 .7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"/></svg>
        <% end %>
      </div>
      <div><%= link_to t('default.terms'), terms_path, class: "block text-left mt-2 md:mt-0" %></div>
      <div><%= link_to t('default.privacy'), privacy_path, class: "block text-left mt-1 md:mt-0" %></div>
    </div>
    <div class='copyright'>
      <div>
        <small>
          <span>© 2023 WS Reviews</span>
        </small>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_before_login_header.html.erb
<header class="px-4 py-4 md:p-4 border-b border-gray-200 fixed w-full z-20 top-0 start-0 bg-[rgba(255,255,255,0.8)]">
  <div class="flex justify-between">
    <h1 class="flex items-center">
      <%= link_to root_path do %>
        <%= image_tag  'logo.png', class: 'block max-w-full w-[80px] md:w-[95px]' %>
      <% end %>
    </h1>

    <div class="flex">
      <button data-modal-target="authentication-modal" data-modal-toggle="authentication-modal" class="mr-2 md:mr-3 px-3 md:px-4 py-2 shadow rounded-lg bg-[rgb(115,207,223)] hover:bg-[rgb(105,189,204)] transition-colors text-sm md:text-base text-white" type="button">
        <%= t('views.header.login') %>
      </button>
    </div>
  </div>
</header>
<%= render 'user_sessions/new' %>

app/views/shared/_error_messages.html.erb
<% if object.errors.present? %>
  <div class="mb-8">
    <ul class="mb-0 text-[rgb(239,123,81)] font-semibold">
      <% object.errors.full_messages.each do |message| %>
        <% if message == 'URLを入力してください' %>
          <li><%= t('default.form.error.url') %></li>
        <% else %>
          <li><%= message %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="my-4 flex justify-center">
    <% if message_type == 'danger' %>
      <%= content_tag(:div, message, class: "p-4 inline-block text-sm text-center text-[rgb(239,123,81)] rounded-lg bg-[rgba(239,123,81,.15)]", role: 'alert') %>
    <% elsif message_type == 'success' %>
      <%= content_tag(:div, message, class: "p-4 inline-block text-sm text-center text-green-800 rounded-lg bg-green-50", role: 'alert') %>
    <% else %>
      <%= content_tag(:div, message, class: "p-4 inline-block text-sm text-center text-blue-800 rounded-lg bg-blue-50", role: 'alert') %>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class="bg-[rgb(166,217,226)] text-white p-4">
  <div class='container text-center mx-auto'>
    <div class="md:flex md:flex-wrap md:gap-6 md:justify-center md:items-center mb-1 text-[0.8rem] md:text-sm">
      <span>
        <%= link_to 'https://github.com/ayuoh/ws-reviews', class: 'fill-white', target: :_blank, rel: "noopener noreferrer" do %>
          <svg xmlns="http://www.w3.org/2000/svg" height="24" width="23.25" viewBox="0 0 496 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3 .3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5 .3-6.2 2.3zm44.2-1.7c-2.9 .7-4.9 2.6-4.6 4.9 .3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3 .7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3 .3 2.9 2.3 3.9 1.6 1 3.6 .7 4.3-.7 .7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3 .7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3 .7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"/></svg>
        <% end %>
      </span>
      <div ><%= link_to t('default.info'), info_path, class: "block text-left mt-2 md:mt-0" %></div>
      <div ><%= link_to t('default.terms'), terms_path, class: "block text-left mt-2 md:mt-0" %></div>
      <div><%= link_to t('default.privacy'), privacy_path, class: "block text-left mt-1 md:mt-0" %></div>
    </div>
    <div class='copyright'>
      <div>
        <small>
          <span>© 2023 WS Reviews</span>
        </small>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="px-4 py-4 md:p-4 border-b border-gray-200 fixed w-full z-20 top-0 start-0 bg-[rgba(255,255,255,0.8)]">
  <div class="flex justify-between">
    <h1 class="flex items-center">
      <%= link_to root_path do %>
        <%= image_tag  'logo.png', class: 'block max-w-full w-[80px] md:w-[95px]' %>
      <% end %>
    </h1>

    <div class="flex items-center">
      <%= link_to '投稿', new_review_path, class: 'mr-2 md:mr-3 px-3 md:px-4 py-2 shadow rounded-lg bg-[rgb(115,207,223)] hover:bg-[rgb(105,189,204)] transition-colors text-sm md:text-base text-white' %>

      <div>
        <button data-collapse-toggle="navbar-sticky" type="button" class="flex items-center"  aria-controls="navbar-sticky" aria-expanded="false">
          <%= image_tag  ActiveDecorator::Decorator.instance.decorate(current_user).avatar_img, class: 'block rounded-[50%] max-w-full w-[40px] md:w-[40px] h-[40px] md:h-[40px] object-cover' %>
        </button>
      </div>
    </div>
  </div>

  <div class="hidden w-full" id="navbar-sticky">
    <div class="flex justify-end">
      <ul class="flex flex-col mt-3 font-medium border border-gray-100 rounded-lg bg-white rtl:space-x-reverse w-[9em] text-right">
        <li>
          <%= link_to t('views.header.profile'), edit_user_path(current_user), class: 'block text-sm w-full text-[rgb(115,207,223)] hover:text-[rgb(105,189,204)] px-2 pt-2 pb-1' %>
        </li>
        <li>
          <%= link_to t('views.header.posted'), own_path(current_user.id), class: 'block text-sm w-full text-[rgb(115,207,223)] hover:text-[rgb(105,189,204)] px-2 py-1' %>
        </li>
        <li>
          <%= link_to t('views.header.favorites'), favorites_reviews_path, class: 'block text-sm w-full text-[rgb(115,207,223)] hover:text-[rgb(105,189,204)] px-2 py-1' %>
        </li>
        <li>
          <%= link_to t('views.header.logout'), logout_path, class: 'block text-sm w-full text-[rgb(115,207,223)] hover:text-[rgb(105,189,204)] px-2 pt-1 pb-2', data: { turbo_method: :delete } %>
        </li>
      </ul>
    </div>
  </div>

  <% if request.path != new_review_path %>
    <%= link_to  new_review_path, class: 'w-[50px] h-[50px] shadow rounded-[50%] bg-[rgba(255,255,255,0.9)] hover:bg-white transition-colors text-sm md:text-base text-white fixed bottom-5 md:bottom-6 right-4 md:right-8 flex items-center justify-center fill-[rgb(115,207,223)] border-[0.5px] border-[rgb(115,207,223)]' do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="new-icon"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M373.5 27.1C388.5 9.9 410.2 0 433 0c43.6 0 79 35.4 79 79c0 22.8-9.9 44.6-27.1 59.6L277.7 319l-10.3-10.3-64-64L193 234.3 373.5 27.1zM170.3 256.9l10.4 10.4 64 64 10.4 10.4-19.2 83.4c-3.9 17.1-16.9 30.7-33.8 35.4L24.4 510.3l95.4-95.4c2.6 .7 5.4 1.1 8.3 1.1c17.7 0 32-14.3 32-32s-14.3-32-32-32s-32 14.3-32 32c0 2.9 .4 5.6 1.1 8.3L1.7 487.6 51.5 310c4.7-16.9 18.3-29.9 35.4-33.8l83.4-19.2z"/></svg>
    <% end %>
  <% end %>
</header>