config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "reviews#index"

  get 'info', to: 'static_pages#info', as: :info
  get 'terms', to: 'static_pages#terms', as: :terms
  get 'privacy', to: 'static_pages#privacy', as: :privacy

  # get 'login', to: 'user_sessions#new', as: :login
  # post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  post "/oauth/:provider/callback" => "oauths#callback"
  get "/oauth/:provider/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#oauth", :as => :auth_at_provider

  delete 'delete', to: 'users#destroy', as: :user_delete
  resources :users, only: %i[edit update]

  resources :reviews do
    get 'favorites', on: :collection
  end
  get 'own/:user_id', to: 'reviews#own_reviews', as: :own

  resources :favorites, only: %i[create destroy]

  get 'tags/search', to: 'tags#search'
  get 'tags/all_search', to: 'tags#all_search'
  get 'organizers/search', to: 'organizers#search'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :require_login, only: %i[index show own_reviews]
  before_action :set_review, only: %i[edit update destroy]

  def index
    order = sort_by
    @q = Review.ransack(params[:q])
    @reviews = @q.result(distinct: true).order(order[0]).order(order[1]).includes(:user, :tags, :web_page).page params[:page]
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = current_user.reviews.new(review_params)
    set_organizer_and_webpage

    @review.satisfaction = @review.satisfaction.round(-1)

    if @review.save && @review.save_tag(tag_params)
      redirect_to root_path, success: t('flash.reviews.success.create')
    else
      flash.now[:danger] = t('flash.reviews.failed.create')
      @org_name = org_param
      @url = url_param
      @tags = params.require(:review)[:tag_names]
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @org_name = @review.web_page.organizer.name
    @url = @review.web_page.url
    @tags = @review.tags.map { |tag| tag.name }.join(', ')
  end

  def update
    update_params = review_params
    set_organizer_and_webpage

    update_params[:satisfaction] = update_params[:satisfaction].to_i.round(-1)

    if @review.update(update_params) && @review.save_tag(tag_params)
      redirect_to review_path(@review), success: t('flash.reviews.success.update')
    else
      flash.now[:danger] = t('flash.reviews.failed.update')
      @org_name = org_param
      @url = url_param
      @tags = params.require(:review)[:tag_names]
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @review.destroy!
    redirect_to root_url, success: t('flash.reviews.success.destroy'), status: :see_other
  end

  def favorites
    @q = current_user.favorite_reviews.ransack(params[:q])
    @reviews = @q.result(distinct: true).includes(:user).order(created_at: :desc).page params[:page]

    recommended_review
  end

  def own_reviews
    @reviews = Review.joins(:user).where(user: { id: params[:user_id] }).includes(:user, :tags, :web_page).order(created_at: :desc).page params[:page]
    render :my_reviews
  end

  private

  def review_params
    params.require(:review).permit(:content, :implementation_start_date, :implementation_last_date, :satisfaction, :genre, :prefecture, :fee)
  end

  def url_param
    params.require(:review).permit(:url)[:url]
  end

  def org_param
    params.require(:review).permit(:org_name)[:org_name]
  end

  def tag_params
    tags = params.require(:review)[:tag_names].split(',')
    tags.map!(&:strip)
  end

  def set_review
    @review = current_user.reviews.find(params[:id])
  end

  def set_organizer_and_webpage
    # web pageの検索。主催者が空欄だったらそのまま検索・保存。主催者が入力していたらorganizer_idを更新。
    web_page = WebPage.find_or_initialize_by(url: url_param)
    if org_param.present?
      # 主催者の検索・保存
      organizer = Organizer.find_or_create_by(name: org_param)
      web_page.update(organizer_id: organizer.id)
    elsif web_page.organizer_id.nil?
      web_page = Organizer.find(1).web_pages.find_or_create_by(url: url_param)
    end
    @review.web_page_id = web_page.id
  end

  def sort_by
    if params[:by] == 'satisfaction'
      if params[:sort] == 'asc'
        first_priority_order = [satisfaction: :asc]
      else
        first_priority_order = [satisfaction: :desc]
      end
      second_priority_order = [created_at: :desc]
    else
      if params[:sort] == 'asc'
        first_priority_order = [created_at: :asc]
      else
        first_priority_order = [created_at: :desc]
      end
      second_priority_order = []
    end

    [first_priority_order, second_priority_order]
  end

  def recommended_review
    favorite = Favorite.where(user_id: current_user.id).order(created_at: :desc).first
    return unless favorite.present?

    # 最近お気に入りにタグがあるか確認
    fav_taggnings = Tagging.where(review_id: favorite.review_id)
    return unless fav_taggnings.present?

    # 最近お気に入りにした投稿のタグをとってくる
    fav_tags = []
    fav_taggnings.each do |ft|
      fav_tags << Tag.joins(taggings: :review).where(id: ft.tag_id).distinct.to_a
    end
    return unless fav_tags.present?

    # 検索したいtag_idを配列に格納する
    fav_tag_ids = []
    fav_tags.each { |t| fav_tag_ids << t[0] }

    # おすすめしたいレビューを取得
    pre_recommended_review = Review.joins(:taggings).where(taggings: { tag_id: fav_tag_ids }).where.not(reviews: { user_id: current_user.id })

    @recommended_review = pre_recommended_review.where.not(id: favorite.review_id).order(created_at: :desc).first
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_crud_buttons.html.erb
<div class="flex gap-3 items-center">
  <%= link_to edit_review_path(review), id: "button-edit-#{review.id}", class: 'fill-[rgb(115,207,223)] hover:fill-[rgb(105,189,204)]' do %>
    <svg xmlns="http://www.w3.org/2000/svg" height="28.8" width="25.2" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M471.6 21.7c-21.9-21.9-57.3-21.9-79.2 0L362.3 51.7l97.9 97.9 30.1-30.1c21.9-21.9 21.9-57.3 0-79.2L471.6 21.7zm-299.2 220c-6.1 6.1-10.8 13.6-13.5 21.9l-29.6 88.8c-2.9 8.6-.6 18.1 5.8 24.6s15.9 8.7 24.6 5.8l88.8-29.6c8.2-2.7 15.7-7.4 21.9-13.5L437.7 172.3 339.7 74.3 172.4 241.7zM96 64C43 64 0 107 0 160V416c0 53 43 96 96 96H352c53 0 96-43 96-96V320c0-17.7-14.3-32-32-32s-32 14.3-32 32v96c0 17.7-14.3 32-32 32H96c-17.7 0-32-14.3-32-32V160c0-17.7 14.3-32 32-32h96c17.7 0 32-14.3 32-32s-14.3-32-32-32H96z"/></svg>
  <% end %>
  <%= link_to review_path(review), id: "button-delete-#{review.id}", data: { turbo_method: :delete, turbo_confirm: t('default.alert.delete_message')  }, class: 'fill-[rgb(115,207,223)] hover:fill-[rgb(105,189,204)]' do %>
    <svg xmlns="http://www.w3.org/2000/svg" height="25.92" width="22.68" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M135.2 17.7C140.6 6.8 151.7 0 163.8 0H284.2c12.1 0 23.2 6.8 28.6 17.7L320 32h96c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 96 0 81.7 0 64S14.3 32 32 32h96l7.2-14.3zM32 128H416V448c0 35.3-28.7 64-64 64H96c-35.3 0-64-28.7-64-64V128zm96 64c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16zm96 0c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16zm96 0c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16z"/></svg>
  <% end %>
</div>

app/views/reviews/_favorite.html.erb
<%= link_to favorites_path(review_id: review.id), id: "favorite-button-for-review-#{review.id}", class:"fill-[rgb(253,223,72)]", data: { turbo_method: :post, toggle: "tooltip", placement: "bottom" }, title: "保存する" do %>
  <svg xmlns="http://www.w3.org/2000/svg" height="25.6" viewBox="0 0 384 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M0 48C0 21.5 21.5 0 48 0l0 48V441.4l130.1-92.9c8.3-6 19.6-6 27.9 0L336 441.4V48H48V0H336c26.5 0 48 21.5 48 48V488c0 9-5 17.2-13 21.3s-17.6 3.4-24.9-1.8L192 397.5 37.9 507.5c-7.3 5.2-16.9 5.9-24.9 1.8S0 497 0 488V48z"/></svg>
<% end %>

app/views/reviews/_favorite_button.html.erb
<% if current_user.favorite?(review) %>
  <%= render 'unfavorite', { review: review } %>
<% else %>
  <%= render 'favorite', { review: review } %>
<% end %>

app/views/reviews/_icon_name.html.erb
<% if review.user.public_twitter %>
  <%= link_to "https://twitter.com/#{review.user.twitter_name}", target: :_blank, rel: "noopener noreferrer" do %>
  <div class="flex items-center">
    <div class="basis-10 md:basis-18 mr-2 md:mr-4 text-xs">
      <%= image_tag review.user.avatar_img, class: 'rounded-[50%] max-w-full min-w-10 w-10 h-10 object-cover' %>
    </div>
    <div>
      <%= review.user.name %>
      <div class="block text-xs md:text-sm text-gray-500">@<%= review.user.twitter_name %></div>
    </div>
  </div>
  <% end %>
<% else %>
  <div class="flex items-center">
    <div class="basis-10 md:basis-18 mr-2 md:mr-4 text-xs">
      <%= image_tag review.user.avatar_img, class: 'rounded-[50%] max-w-full min-w-10 w-10 h-10 object-cover' %>
    </div>
    <div>
      <%= review.user.name %>
    </div>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div class="flex justify-around flex-col md:shadow md:rounded-lg px-4 py-4 md:pl-8 md:pr-7 md:pt-5 md:pb-4 md:m-10 border-b last:border-b-0 border-b-[rgb(245, 240, 230)] card">
  <div class="flex justify-between items-start">
    <!-- icon -->
    <div class="flex items-center link-on-card">
      <%= link_to own_path(review.user.id), class: 'hover:opacity-80' do %>
        <div class="flex items-center text-sm">
            <%= image_tag review.user.avatar_img, class: 'rounded-[50%] max-w-full min-w-10 w-10 h-10 mr-2 object-cover' %><%= review.user.name %>
        </div>
      <% end %>
    </div>
    <div class="flex gap-2 items-center">
      <!-- ボタン -->
      <div class="text-right text-xs flex items-center link-on-card">
        <% if logged_in? %>
          <% if current_user.own?(review) %>
            <%= render 'reviews/share_button', review: review %>
          <% else %>
            <%= render 'reviews/favorite_button', review: review %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- 満足度 -->
  <div class="flex items-center gap-2 flex-row mt-3 mb-3 font-handwriting">
    <div class="text-sm">
      <%= Review.human_attribute_name(:satisfaction) %>
    </div>
    <div class="w-[calc(100%-7.5rem)] relative">
      <div class="w-[calc(100%-1px)] h-[calc(1rem-0.2px)] rounded-lg satisfaction absolute top-[-7.9px]"></div>
      <div class="w-full h-4 rounded-lg bg-gradient-to-r from-[transparent] from-<%= review.satisfaction %> to-gray-100 to-<%= review.satisfaction %> absolute top-[-8px]"></div>
    </div>
    <div class="text-xs tracking-[-0.1em]"><%= review.evaluate_satisfaction %></div>
  </div>

  <!-- review対象 -->
  <% ogp = OpenGraph.new(review.web_page.url) %>
  <%= link_to review.web_page.url, target: :_blank, rel: "noopener noreferrer", class: 'card-ogp' do %>
    <div class="flex border border-solid border-gray-200 rounded-2xl h-20 md:h-32">
      <div class="flex items-center w-full">
        <div class="basis-[5.5rem] md:basis-40 mr-2 md:mr-3 h-full w-1/4"><%= image_tag ogp.images[0] || "ogp.png", class: 'rounded-l-[0.9rem] h-full object-cover object-center' %></div>

        <div class="pr-4 w-3/4">
          <p class="line-clamp-1 text-sm font-bold"><%= review.web_page.organizer.name %></p>
          <p class="line-clamp-1 text-sm"><%= review.ogp_title(ogp.title, true) %></p>
          <p class="text-gray-400 text-[0.8rem] line-clamp-1 md:line-clamp-2 leading-5"><%= ogp.description || "" %></p>
        </div>
      </div>
    </div>
  <% end %>

  <div class="flex-grow">
    <!-- ジャンル・タグ -->
    <div class="pt-2 flex flex-wrap gap-y-[0.2rem]">
      <span class="block text-sm rounded py-[1.5px] px-2 bg-[rgb(239,123,81)] text-white"><%= review.genre_i18n %></span>
    </div>
    <% if review.tags.present? %>
      <div class="pt-1 flex flex-wrap gap-y-[0.2rem] gap-x-1">
        <% review.tags.each do |tag| %>
          <span class="inline-block text-sm rounded py-[1.5px] px-2 bg-[rgb(166,217,226)] text-white"><%= tag.name %></span>
        <% end %>
      </div>
    <% end %>

    <!-- review内容 -->
    <div class="hover:text-gray-950 rounded-lg pt-3 pb-2 card-sentence">
      <%= link_to review_path(review) do %>
        <div class="whitespace-pre-line line-clamp-5"><%= review.content %></div>
      <% end %>
    </div>

    <!-- 投稿日 -->
    <div class="text-[0.7rem] text-gray-500 text-right pr-1 mt-1">
      <%= review.format_created_at %>
    </div>
  </div>
</div>

app/views/reviews/_share_button.html.erb
<%= link_to "https://twitter.com/share?url=#{review_url(review)}&text=ワークショップのレビューをしたよ！%0a#{review.title}%0a%0a", class: 'fill-[rgb(115,207,223)] hover:fill-[rgb(105,189,204)]', target: '_blank', data: { toggle: "tooltip", placement: "bottom" }, title: "Xでシェア" do %>
  <svg xmlns="http://www.w3.org/2000/svg" height="27.2" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H384c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64zm297.1 84L257.3 234.6 379.4 396H283.8L209 298.1 123.3 396H75.8l111-126.9L69.7 116h98l67.7 89.5L313.6 116h47.5zM323.3 367.6L153.4 142.9H125.1L296.9 367.6h26.3z"/></svg>
<% end %>

app/views/reviews/_sort_buttons.html.erb
<div class="flex justify-end px-4 pt-5 md:pl-8 md:pr-7 md:pt-6 text-xs text-gray-400">
  <%= link_to '新着順', reviews_path(by: 'created_at'), id: 'recent', class: 'flex items-center justify-center px-3 h-8 border border-gray-300 rounded-s-lg hover:bg-gray-100 select-button' %>
  <%= link_to '投稿順', reviews_path(by: 'created_at', sort: 'asc'), id: 'least-recent', class: 'flex items-center justify-center px-3 h-8 border-y border-gray-300 hover:bg-gray-100 select-button' %>
  <%= link_to '満足順', reviews_path(by: 'satisfaction'), id: 'satisfaction', class: 'flex items-center justify-center px-3 h-8 border border-gray-300 rounded-e-lg hover:bg-gray-100 select-button' %>
</div>

<%= javascript_include_tag "sort_button.js" %>

app/views/reviews/_tags.html.erb
<div class="mt-2 mb-6 flex flex-wrap gap-y-[0.2rem] gap-x-1">
  <% @review.tags.each do |tag| %>
    <span class="inline-block mr-1 text-sm rounded py-[2px] px-2 bg-[rgb(166,217,226)] text-white"><%= tag.name %></span>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="py-8 px-4 mx-auto max-w-2xl">
  <div class="mb-6">
    <p class="text-sm text-[rgb(239,123,81)]"><%= t('.caution') %></p>
  </div>
  <%= render 'form', { review: @review, url: review_path(@review), submit: 'reviews.edit.submit' } %>
</div>

app/views/reviews/favorites.html.erb
<% if @reviews.present? %>
  <div>
    <% if @recommended_review.present? %>
      <%= render 'reviews/recommended_review', review: @recommended_review %>
    <% end %>
    <%= render @reviews %>
  </div>
<% else %>
  <div class="text-center pt-10 pb-4 md:pb-0"><%= t('default.message.favorites') %></div>
<% end %>
<div class="text-center my-4 md:my-0"><%= paginate @reviews %></div>

app/views/reviews/my_reviews.html.erb
<% if @reviews.present? %>
  <div>
    <%= render @reviews %>
  </div>
<% else %>
  <div class="text-center pt-10 pb-4 md:pb-0"><%= t('default.message.my_reviews') %></div>
<% end %>
<div class="text-center my-4 md:my-0"><%= paginate @reviews %></div>

app/views/reviews/reviews.html.erb
<div class="md:container">
  <%= render 'reviews/review'%>
</div>

app/views/reviews/show.html.erb
<div class="px-4 pt-6 pb-4 md:pt-4 md:pb-5 md:m-10 md:mb-0">
  <div class="flex justify-between">
    <!-- icon -->
    <%= render 'reviews/icon_name', review: @review %>

    <% if logged_in? %>
      <% if current_user.own?(@review) %>
        <div class="flex items-end gap-4">
          <%= render 'reviews/share_button', review: @review %>
          <%= render 'reviews/crud_buttons', review: @review %>
        </div>
      <% else %>
        <%= render 'reviews/favorite_button', review: @review %>
      <% end %>
    <% end %>
  </div>

  <div class="flex flex-wrap gap-2 items-center justify-between mt-6">
    <!-- review詳細 -->
    <div class="w-[52%] max-w-[52%] text-xs text-right">
      <ul>
        <li class="pb-1 border-b border-dotted border-[rgb(166,217,226)]">
          <div><%= @review.format_created_at %></div>
        </li>

        <li class="mt-3 pb-1 border-b border-dotted border-[rgb(166,217,226)]">
          <div><%= @review.implementation_term %></div>
        </li>

        <li class="mt-3 pb-1 border-b border-dotted border-[rgb(166,217,226)]">
          <div><%= @review.format_organizer %></div>
        </li>

        <li class="mt-3 pb-1 border-b border-dotted border-[rgb(166,217,226)]">
          <div><%= @review.format_prefecture %></div>
        </li>

        <li class="mt-3 pb-1 border-b border-dotted border-[rgb(166,217,226)]">
          <div><%= @review.format_fee %></div>
        </li>
      </ul>
    </div>

    <!-- review対象 -->
    <% ogp = OpenGraph.new(@review.web_page.url) %>
    <%= link_to @review.web_page.url, class: 'max-w-[45%]', target: :_blank, rel: "noopener noreferrer" do %>
      <div class="border border-solid border-gray-200 rounded-2xl relative max-w-full">
        <div>
          <%= image_tag ogp.images[0] || "ogp.png", class: 'block rounded-[0.9rem] max-w-full object-cover object-center min-h-[150px]' %>

          <span class="px-2 pt-2 md:pt-1 pb-2 absolute bottom-0 bg-[rgba(0,0,0,.6)] rounded-b-[0.9rem] box-border w-[-webkit-fill-available]">
            <span class="line-clamp-1 text-gray-300 text-xs md:text-base"><%= @review.ogp_title(ogp.title) %></span>
            <span class="hidden text-[0.7em] md:line-clamp-1 leading-5 text-gray-400"><%= @review.web_page.url %></span>
            <span class="hidden text-[0.7em] md:line-clamp-1 leading-5 text-gray-400"><%= ogp.description || "" %></span>
          </span>
        </div>
      </div>
    <% end %>
  </div>

  <div class="mt-2">
    <!-- ジャンル・タグ -->
    <div class="flex flex-wrap gap-y-[0.2rem]">
      <span class="block text-sm rounded py-[1.5px] px-2 bg-[rgb(239,123,81)] text-white"><%= @review.genre_i18n %></span>
    </div>
    <% if @review.tags.present? %>
      <div class="pt-1 flex flex-wrap gap-y-[0.2rem] gap-x-1">
        <% @review.tags.each do |tag| %>
          <span class="inline-block text-sm rounded py-[1.5px] px-2 bg-[rgb(166,217,226)] text-white"><%= tag.name %></span>
        <% end %>
      </div>
    <% end %>

    <!-- 満足度 -->
    <div class="flex items-center gap-2 flex-row mt-3 mb-3 font-handwriting">
      <div class="text-sm">
        <%= Review.human_attribute_name(:satisfaction) %>
      </div>
      <div class="w-[calc(100%-7.5rem)] relative">
        <div class="w-[calc(100%-1px)] h-[calc(1rem-0.2px)] rounded-lg satisfaction absolute top-[-7.9px]"></div>
        <div class="w-full h-4 rounded-lg bg-gradient-to-r from-[transparent] from-<%= @review.satisfaction %> to-gray-100 to-<%= @review.satisfaction %> absolute top-[-8px]"></div>
      </div>
      <div class="text-xs tracking-[-0.1em]"><%= @review.evaluate_satisfaction %></div>
    </div>

    <!-- reviewコンテンツ -->
    <div class="relative mt-4">
      <div class="text-right text-xs absolute top-0 right-0">
      </div>
      <div class="mt-4 whitespace-pre-line leading-[2.3rem]"><span class="pb-[3px] border-b border-dotted border-[rgb(166,217,226)]"><%= @review.content %></span></div>
    </div>
  </div>
  <%= link_to '一覧に戻る', reviews_path, class: 'block w-[5em] mx-auto mt-4 md:mt-8 text-xs md:text-[15px] text-[rgb(166,217,226)]' %>
</div>