config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "reviews#index"

  get 'info', to: 'static_pages#info', as: :info
  get 'terms', to: 'static_pages#terms', as: :terms
  get 'privacy', to: 'static_pages#privacy', as: :privacy

  # get 'login', to: 'user_sessions#new', as: :login
  # post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  post "/oauth/:provider/callback" => "oauths#callback"
  get "/oauth/:provider/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#oauth", :as => :auth_at_provider

  delete 'delete', to: 'users#destroy', as: :user_delete
  resources :users, only: %i[edit update]

  resources :reviews do
    get 'favorites', on: :collection
  end
  get 'own/:user_id', to: 'reviews#own_reviews', as: :own

  resources :favorites, only: %i[create destroy]

  get 'tags/search', to: 'tags#search'
  get 'tags/all_search', to: 'tags#all_search'
  get 'organizers/search', to: 'organizers#search'
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to root_path, success: t('flash.user_sessions.login')
    else
      flash.now[:danger] = t('flash.user_sessions.cant_login')
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('flash.user_sessions.logout')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_new.html.erb
<!-- Main modal -->
<div id="authentication-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 mx-auto justify-center items-center w-3/4 max-w-[350px] md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-2xl max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded shadow">
            <!-- Modal header -->
            <div class="flex items-center justify-between px-2 md:px-3 border-b rounded-t">
                <h3 class="text-xl p-2 pt-3">
                    <%= t('user_sessions.login') %>
                </h3>
                <button type="button" class="end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-hide="authentication-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!-- Modal body -->
            <div class="p-4 md:p-5 space-y-4">
                <div class="text-base leading-relaxed">
                    <p class="mb-4 text-sm">
                        <%= link_to t('default.terms'), terms_path, class: 'text-[rgb(115,207,223)]', target: :_blank, rel: "noopener noreferrer" %><%= t('default.words.and') %><%= link_to t('default.privacy'), privacy_path, class: 'text-[rgb(115,207,223)]', target: :_blank, rel: "noopener noreferrer" %><%= t('user_sessions.login_message') %>
                    </p>
                    <%= link_to auth_at_provider_path(provider: :twitter), class: 'text-sm sm:text-base flex items-center justify-center w-full rounded border-2 focus:outline-none focus:border-[rgb(166,217,226)] hover:border-[rgb(166,217,226)] transition', data: { modal: 'authentication-modal' } do %>
                        <%= image_tag 'xlogo.svg', class: 'p-2 mr-1' %>
                        <%= t('user_sessions.x') %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>